pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Build'
            }
        }
        stage('Test') {
            steps {
               echo 'TEST'
            }
        }
        stage('Deliver') {
            steps {
               echo 'Deliver'
            }
        }
        stage('Complete') {
            steps {
                echo 'Completed'
            }
        }
    }
}
